install: gradle wrapper --gradle-version 4.2

sudo: required
before_script:
  - chmod +x gradlew

language: java

jdk:
  - oraclejdk8

after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)